# Generated by Django 3.2.25 on 2025-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=45)),
                ('departement', models.CharField(max_length=45)),
                ('experience', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('qualification', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(max_length=450)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
