# Generated by Django 3.2.25 on 2025-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_name', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
